#pragma once

#define VERSION_MAJOR   2
#define VERSION_MINOR   7
#define VERSION_BUILD   7

#define VERSION_MAJOR_STR   "2"
#define VERSION_MINOR_STR   "7"
#define VERSION_BUILD_STR   "7"
#define VERSION_FULL ((VERSION_MAJOR*100)+(VERSION_MINOR*10)+VERSION_BUILD)

#define STRINGIZER(arg) #arg
//#define VERSION_STRING(major,minor) STRINGIZER(major)##".0."##STRINGIZER(minor)
//#define VERSION_STRING STRINGIZER(VERSION_MAJOR)##".0."##STRINGIZER(VERSION_MINOR)
#define VERSION_STRING VERSION_MAJOR_STR "." VERSION_MINOR_STR "." VERSION_BUILD_STR
//#temp line#